development:
  app_id: <%= ENV['FB_APP_ID_TEST'] %>
  secret_key: <%= ENV['FB_SECRET_TEST'] %>
  app_url: //serene-hollows-3948.herokuapp.com
  fb_url: https://apps.facebook.com/zazen-test-app/
  channel_url: //serene-hollows-3948.herokuapp.com/facebook/channel

production:
  app_id: <%= ENV['FB_APP_ID_TEST'] %>
  secret_key: <%= ENV['FB_SECRET_TEST'] %>
  app_url: //serene-hollows-3948.herokuapp.com
  fb_url: https://apps.facebook.com/zazen-test-app/
  channel_url: //serene-hollows-3948.herokuapp.com/facebook/channel
